################################################################################
# Automatically-generated file. Do not edit!
################################################################################

TREE_TYPE = TWO_LEVEL_TREE

IDIR = ../src/auxi/LKH/INCLUDE
CFLAGS = -O3 -Wall -I$(IDIR) -D$(TREE_TYPE)

# Add inputs and outputs from these tool invocations to the build variables
CPP_SRCS += \
../src/auxi/LKH/Activate.c \
../src/auxi/LKH/AddCandidate.c \
../src/auxi/LKH/AddExtraCandidates.c \
../src/auxi/LKH/AddTourCandidates.c \
../src/auxi/LKH/AdjustCandidateSet.c \
../src/auxi/LKH/AdjustClusters.c \
../src/auxi/LKH/AllocateStructures.c \
../src/auxi/LKH/Ascent.c \
../src/auxi/LKH/Best2OptMove.c \
../src/auxi/LKH/Best3OptMove.c \
../src/auxi/LKH/Best4OptMove.c \
../src/auxi/LKH/Best5OptMove.c \
../src/auxi/LKH/BestKOptMove.c \
../src/auxi/LKH/BestSpecialOptMove.c \
../src/auxi/LKH/Between.c \
../src/auxi/LKH/Between_SL.c \
../src/auxi/LKH/Between_SSL.c \
../src/auxi/LKH/BIT.c \
../src/auxi/LKH/BridgeGain.c \
../src/auxi/LKH/BuildKDTree.c \
../src/auxi/LKH/CandidateReport.c \
../src/auxi/LKH/C.c \
../src/auxi/LKH/ChooseInitialTour.c \
../src/auxi/LKH/Connect.c \
../src/auxi/LKH/CreateCandidateSet.c \
../src/auxi/LKH/CreateDelaunayCandidateSet.c \
../src/auxi/LKH/CreateNNCandidateSet.c \
../src/auxi/LKH/Create_POPMUSIC_CandidateSet.c \
../src/auxi/LKH/CreateQuadrantCandidateSet.c \
../src/auxi/LKH/CTSP_InitialTour.c \
../src/auxi/LKH/CVRP_InitialTour.c \
../src/auxi/LKH/Delaunay.c \
../src/auxi/LKH/Distance.c \
../src/auxi/LKH/Distance_MTSP.c \
../src/auxi/LKH/Distance_SOP.c \
../src/auxi/LKH/Distance_SPECIAL.c \
../src/auxi/LKH/eprintf.c \
../src/auxi/LKH/ERXT.c \
../src/auxi/LKH/Excludable.c \
../src/auxi/LKH/Exclude.c \
../src/auxi/LKH/FindTour.c \
../src/auxi/LKH/FixedOrCommonCandidates.c \
../src/auxi/LKH/Flip.c \
../src/auxi/LKH/Flip_SL.c \
../src/auxi/LKH/Flip_SSL.c \
../src/auxi/LKH/Forbidden.c \
../src/auxi/LKH/FreeStructures.c \
../src/auxi/LKH/fscanint.c \
../src/auxi/LKH/Gain23.c \
../src/auxi/LKH/GenerateCandidates.c \
../src/auxi/LKH/Genetic.c \
../src/auxi/LKH/GeoConversion.c \
../src/auxi/LKH/GetTime.c \
../src/auxi/LKH/gpx.c \
../src/auxi/LKH/GreedyTour.c \
../src/auxi/LKH/Hashing.c \
../src/auxi/LKH/Heap.c \
../src/auxi/LKH/Improvement.c \
../src/auxi/LKH/IsBackboneCandidate.c \
../src/auxi/LKH/IsCandidate.c \
../src/auxi/LKH/IsCommonEdge.c \
../src/auxi/LKH/IsPossibleCandidate.c \
../src/auxi/LKH/KSwapKick.c \
../src/auxi/LKH/LinKernighan.c \
../src/auxi/LKH/LKH_Lib.c \
../src/auxi/LKH/Make2OptMove.c \
../src/auxi/LKH/Make3OptMove.c \
../src/auxi/LKH/Make4OptMove.c \
../src/auxi/LKH/Make5OptMove.c \
../src/auxi/LKH/MakeKOptMove.c \
../src/auxi/LKH/MergeTourWithBestTour.c \
../src/auxi/LKH/MergeWithTourGPX2.c \
../src/auxi/LKH/MergeWithTourIPT.c \
../src/auxi/LKH/Minimum1TreeCost.c \
../src/auxi/LKH/MinimumSpanningTree.c \
../src/auxi/LKH/MTSP2TSP.c \
../src/auxi/LKH/MTSP_InitialTour.c \
../src/auxi/LKH/MTSP_Report.c \
../src/auxi/LKH/MTSP_WriteSolution.c \
../src/auxi/LKH/NormalizeNodeList.c \
../src/auxi/LKH/NormalizeSegmentList.c \
../src/auxi/LKH/OrderCandidateSet.c \
../src/auxi/LKH/PatchCycles.c \
../src/auxi/LKH/PDPTW_Reduce.c \
../src/auxi/LKH/Penalty_1_PDTSP.c \
../src/auxi/LKH/Penalty_ACVRP.c \
../src/auxi/LKH/Penalty_BWTSP.c \
../src/auxi/LKH/Penalty_CCVRP.c \
../src/auxi/LKH/Penalty_CTSP.c \
../src/auxi/LKH/Penalty_CVRP.c \
../src/auxi/LKH/Penalty_CVRPTW.c \
../src/auxi/LKH/Penalty_M1_PDTSP.c \
../src/auxi/LKH/Penalty_MLP.c \
../src/auxi/LKH/Penalty_M_PDTSP.c \
../src/auxi/LKH/Penalty_MTSP.c \
../src/auxi/LKH/Penalty_OVRP.c \
../src/auxi/LKH/Penalty_PDPTW.c \
../src/auxi/LKH/Penalty_PDTSP.c \
../src/auxi/LKH/Penalty_PDTSPF.c \
../src/auxi/LKH/Penalty_PDTSPL.c \
../src/auxi/LKH/Penalty_RCTVRP.c \
../src/auxi/LKH/Penalty_SOP.c \
../src/auxi/LKH/Penalty_TRP.c \
../src/auxi/LKH/Penalty_TSPDL.c \
../src/auxi/LKH/Penalty_TSPPD.c \
../src/auxi/LKH/Penalty_TSPTW.c \
../src/auxi/LKH/Penalty_VRPB.c \
../src/auxi/LKH/Penalty_VRPBTW.c \
../src/auxi/LKH/Penalty_VRPPD.c \
../src/auxi/LKH/printff.c \
../src/auxi/LKH/PrintParameters.c \
../src/auxi/LKH/Random.c \
../src/auxi/LKH/ReadCandidates.c \
../src/auxi/LKH/ReadEdges.c \
../src/auxi/LKH/ReadLine.c \
../src/auxi/LKH/ReadParameters.c \
../src/auxi/LKH/ReadPenalties.c \
../src/auxi/LKH/ReadProblem.c \
../src/auxi/LKH/RecordBestTour.c \
../src/auxi/LKH/RecordBetterTour.c \
../src/auxi/LKH/RemoveFirstActive.c \
../src/auxi/LKH/ResetCandidateSet.c \
../src/auxi/LKH/RestoreTour.c \
../src/auxi/LKH/SegmentSize.c \
../src/auxi/LKH/Sequence.c \
../src/auxi/LKH/SFCTour.c \
../src/auxi/LKH/SINTEF_WriteSolution.c \
../src/auxi/LKH/SolveCompressedSubproblem.c \
../src/auxi/LKH/SolveDelaunaySubproblems.c \
../src/auxi/LKH/SolveKarpSubproblems.c \
../src/auxi/LKH/SolveKCenterSubproblems.c \
../src/auxi/LKH/SolveKMeansSubproblems.c \
../src/auxi/LKH/SolveRoheSubproblems.c \
../src/auxi/LKH/SolveSFCSubproblems.c \
../src/auxi/LKH/SolveSubproblemBorderProblems.c \
../src/auxi/LKH/SolveSubproblem.c \
../src/auxi/LKH/SolveTourSegmentSubproblems.c \
../src/auxi/LKH/SOP_InitialTour.c \
../src/auxi/LKH/SOP_RepairTour.c \
../src/auxi/LKH/SOP_Report.c \
../src/auxi/LKH/Statistics.c \
../src/auxi/LKH/StatusReport.c \
../src/auxi/LKH/StoreTour.c \
../src/auxi/LKH/SymmetrizeCandidateSet.c \
../src/auxi/LKH/TrimCandidateSet.c \
../src/auxi/LKH/TSPDL_InitialTour.c \
../src/auxi/LKH/TSPTW_MakespanCost.c \
../src/auxi/LKH/TSPTW_Reduce.c \
../src/auxi/LKH/VRPB_Reduce.c \
../src/auxi/LKH/WriteCandidates.c \
../src/auxi/LKH/WritePenalties.c \
../src/auxi/LKH/WriteTour.c


OBJS += \
./src/auxi/LKH/Activate.o \
./src/auxi/LKH/AddCandidate.o \
./src/auxi/LKH/AddExtraCandidates.o \
./src/auxi/LKH/AddTourCandidates.o \
./src/auxi/LKH/AdjustCandidateSet.o \
./src/auxi/LKH/AdjustClusters.o \
./src/auxi/LKH/AllocateStructures.o \
./src/auxi/LKH/Ascent.o \
./src/auxi/LKH/Best2OptMove.o \
./src/auxi/LKH/Best3OptMove.o \
./src/auxi/LKH/Best4OptMove.o \
./src/auxi/LKH/Best5OptMove.o \
./src/auxi/LKH/BestKOptMove.o \
./src/auxi/LKH/BestSpecialOptMove.o \
./src/auxi/LKH/Between.o \
./src/auxi/LKH/Between_SL.o \
./src/auxi/LKH/Between_SSL.o \
./src/auxi/LKH/BIT.o \
./src/auxi/LKH/BridgeGain.o \
./src/auxi/LKH/BuildKDTree.o \
./src/auxi/LKH/CandidateReport.o \
./src/auxi/LKH/C.o \
./src/auxi/LKH/ChooseInitialTour.o \
./src/auxi/LKH/Connect.o \
./src/auxi/LKH/CreateCandidateSet.o \
./src/auxi/LKH/CreateDelaunayCandidateSet.o \
./src/auxi/LKH/CreateNNCandidateSet.o \
./src/auxi/LKH/Create_POPMUSIC_CandidateSet.o \
./src/auxi/LKH/CreateQuadrantCandidateSet.o \
./src/auxi/LKH/CTSP_InitialTour.o \
./src/auxi/LKH/CVRP_InitialTour.o \
./src/auxi/LKH/Delaunay.o \
./src/auxi/LKH/Distance.o \
./src/auxi/LKH/Distance_MTSP.o \
./src/auxi/LKH/Distance_SOP.o \
./src/auxi/LKH/Distance_SPECIAL.o \
./src/auxi/LKH/eprintf.o \
./src/auxi/LKH/ERXT.o \
./src/auxi/LKH/Excludable.o \
./src/auxi/LKH/Exclude.o \
./src/auxi/LKH/FindTour.o \
./src/auxi/LKH/FixedOrCommonCandidates.o \
./src/auxi/LKH/Flip.o \
./src/auxi/LKH/Flip_SL.o \
./src/auxi/LKH/Flip_SSL.o \
./src/auxi/LKH/Forbidden.o \
./src/auxi/LKH/FreeStructures.o \
./src/auxi/LKH/fscanint.o \
./src/auxi/LKH/Gain23.o \
./src/auxi/LKH/GenerateCandidates.o \
./src/auxi/LKH/Genetic.o \
./src/auxi/LKH/GeoConversion.o \
./src/auxi/LKH/GetTime.o \
./src/auxi/LKH/gpx.o \
./src/auxi/LKH/GreedyTour.o \
./src/auxi/LKH/Hashing.o \
./src/auxi/LKH/Heap.o \
./src/auxi/LKH/Improvement.o \
./src/auxi/LKH/IsBackboneCandidate.o \
./src/auxi/LKH/IsCandidate.o \
./src/auxi/LKH/IsCommonEdge.o \
./src/auxi/LKH/IsPossibleCandidate.o \
./src/auxi/LKH/KSwapKick.o \
./src/auxi/LKH/LinKernighan.o \
./src/auxi/LKH/LKH_Lib.o \
./src/auxi/LKH/Make2OptMove.o \
./src/auxi/LKH/Make3OptMove.o \
./src/auxi/LKH/Make4OptMove.o \
./src/auxi/LKH/Make5OptMove.o \
./src/auxi/LKH/MakeKOptMove.o \
./src/auxi/LKH/MergeTourWithBestTour.o \
./src/auxi/LKH/MergeWithTourGPX2.o \
./src/auxi/LKH/MergeWithTourIPT.o \
./src/auxi/LKH/Minimum1TreeCost.o \
./src/auxi/LKH/MinimumSpanningTree.o \
./src/auxi/LKH/MTSP2TSP.o \
./src/auxi/LKH/MTSP_InitialTour.o \
./src/auxi/LKH/MTSP_Report.o \
./src/auxi/LKH/MTSP_WriteSolution.o \
./src/auxi/LKH/NormalizeNodeList.o \
./src/auxi/LKH/NormalizeSegmentList.o \
./src/auxi/LKH/OrderCandidateSet.o \
./src/auxi/LKH/PatchCycles.o \
./src/auxi/LKH/PDPTW_Reduce.o \
./src/auxi/LKH/Penalty_1_PDTSP.o \
./src/auxi/LKH/Penalty_ACVRP.o \
./src/auxi/LKH/Penalty_BWTSP.o \
./src/auxi/LKH/Penalty_CCVRP.o \
./src/auxi/LKH/Penalty_CTSP.o \
./src/auxi/LKH/Penalty_CVRP.o \
./src/auxi/LKH/Penalty_CVRPTW.o \
./src/auxi/LKH/Penalty_M1_PDTSP.o \
./src/auxi/LKH/Penalty_MLP.o \
./src/auxi/LKH/Penalty_M_PDTSP.o \
./src/auxi/LKH/Penalty_MTSP.o \
./src/auxi/LKH/Penalty_OVRP.o \
./src/auxi/LKH/Penalty_PDPTW.o \
./src/auxi/LKH/Penalty_PDTSP.o \
./src/auxi/LKH/Penalty_PDTSPF.o \
./src/auxi/LKH/Penalty_PDTSPL.o \
./src/auxi/LKH/Penalty_RCTVRP.o \
./src/auxi/LKH/Penalty_SOP.o \
./src/auxi/LKH/Penalty_TRP.o \
./src/auxi/LKH/Penalty_TSPDL.o \
./src/auxi/LKH/Penalty_TSPPD.o \
./src/auxi/LKH/Penalty_TSPTW.o \
./src/auxi/LKH/Penalty_VRPB.o \
./src/auxi/LKH/Penalty_VRPBTW.o \
./src/auxi/LKH/Penalty_VRPPD.o \
./src/auxi/LKH/printff.o \
./src/auxi/LKH/PrintParameters.o \
./src/auxi/LKH/Random.o \
./src/auxi/LKH/ReadCandidates.o \
./src/auxi/LKH/ReadEdges.o \
./src/auxi/LKH/ReadLine.o \
./src/auxi/LKH/ReadParameters.o \
./src/auxi/LKH/ReadPenalties.o \
./src/auxi/LKH/ReadProblem.o \
./src/auxi/LKH/RecordBestTour.o \
./src/auxi/LKH/RecordBetterTour.o \
./src/auxi/LKH/RemoveFirstActive.o \
./src/auxi/LKH/ResetCandidateSet.o \
./src/auxi/LKH/RestoreTour.o \
./src/auxi/LKH/SegmentSize.o \
./src/auxi/LKH/Sequence.o \
./src/auxi/LKH/SFCTour.o \
./src/auxi/LKH/SINTEF_WriteSolution.o \
./src/auxi/LKH/SolveCompressedSubproblem.o \
./src/auxi/LKH/SolveDelaunaySubproblems.o \
./src/auxi/LKH/SolveKarpSubproblems.o \
./src/auxi/LKH/SolveKCenterSubproblems.o \
./src/auxi/LKH/SolveKMeansSubproblems.o \
./src/auxi/LKH/SolveRoheSubproblems.o \
./src/auxi/LKH/SolveSFCSubproblems.o \
./src/auxi/LKH/SolveSubproblemBorderProblems.o \
./src/auxi/LKH/SolveSubproblem.o \
./src/auxi/LKH/SolveTourSegmentSubproblems.o \
./src/auxi/LKH/SOP_InitialTour.o \
./src/auxi/LKH/SOP_RepairTour.o \
./src/auxi/LKH/SOP_Report.o \
./src/auxi/LKH/Statistics.o \
./src/auxi/LKH/StatusReport.o \
./src/auxi/LKH/StoreTour.o \
./src/auxi/LKH/SymmetrizeCandidateSet.o \
./src/auxi/LKH/TrimCandidateSet.o \
./src/auxi/LKH/TSPDL_InitialTour.o \
./src/auxi/LKH/TSPTW_MakespanCost.o \
./src/auxi/LKH/TSPTW_Reduce.o \
./src/auxi/LKH/VRPB_Reduce.o \
./src/auxi/LKH/WriteCandidates.o \
./src/auxi/LKH/WritePenalties.o \
./src/auxi/LKH/WriteTour.o

CPP_DEPS += \
./src/auxi/LKH/Activate.d \
./src/auxi/LKH/AddCandidate.d \
./src/auxi/LKH/AddExtraCandidates.d \
./src/auxi/LKH/AddTourCandidates.d \
./src/auxi/LKH/AdjustCandidateSet.d \
./src/auxi/LKH/AdjustClusters.d \
./src/auxi/LKH/AllocateStructures.d \
./src/auxi/LKH/Ascent.d \
./src/auxi/LKH/Best2OptMove.d \
./src/auxi/LKH/Best3OptMove.d \
./src/auxi/LKH/Best4OptMove.d \
./src/auxi/LKH/Best5OptMove.d \
./src/auxi/LKH/BestKOptMove.d \
./src/auxi/LKH/BestSpecialOptMove.d \
./src/auxi/LKH/Between.d \
./src/auxi/LKH/Between_SL.d \
./src/auxi/LKH/Between_SSL.d \
./src/auxi/LKH/BIT.d \
./src/auxi/LKH/BridgeGain.d \
./src/auxi/LKH/BuildKDTree.d \
./src/auxi/LKH/CandidateReport.d \
./src/auxi/LKH/C.d \
./src/auxi/LKH/ChooseInitialTour.d \
./src/auxi/LKH/Connect.d \
./src/auxi/LKH/CreateCandidateSet.d \
./src/auxi/LKH/CreateDelaunayCandidateSet.d \
./src/auxi/LKH/CreateNNCandidateSet.d \
./src/auxi/LKH/Create_POPMUSIC_CandidateSet.d \
./src/auxi/LKH/CreateQuadrantCandidateSet.d \
./src/auxi/LKH/CTSP_InitialTour.d \
./src/auxi/LKH/CVRP_InitialTour.d \
./src/auxi/LKH/Delaunay.d \
./src/auxi/LKH/Distance.d \
./src/auxi/LKH/Distance_MTSP.d \
./src/auxi/LKH/Distance_SOP.d \
./src/auxi/LKH/Distance_SPECIAL.d \
./src/auxi/LKH/eprintf.d \
./src/auxi/LKH/ERXT.d \
./src/auxi/LKH/Excludable.d \
./src/auxi/LKH/Exclude.d \
./src/auxi/LKH/FindTour.d \
./src/auxi/LKH/FixedOrCommonCandidates.d \
./src/auxi/LKH/Flip.d \
./src/auxi/LKH/Flip_SL.d \
./src/auxi/LKH/Flip_SSL.d \
./src/auxi/LKH/Forbidden.d \
./src/auxi/LKH/FreeStructures.d \
./src/auxi/LKH/fscanint.d \
./src/auxi/LKH/Gain23.d \
./src/auxi/LKH/GenerateCandidates.d \
./src/auxi/LKH/Genetic.d \
./src/auxi/LKH/GeoConversion.d \
./src/auxi/LKH/GetTime.d \
./src/auxi/LKH/gpx.d \
./src/auxi/LKH/GreedyTour.d \
./src/auxi/LKH/Hashing.d \
./src/auxi/LKH/Heap.d \
./src/auxi/LKH/Improvement.d \
./src/auxi/LKH/IsBackboneCandidate.d \
./src/auxi/LKH/IsCandidate.d \
./src/auxi/LKH/IsCommonEdge.d \
./src/auxi/LKH/IsPossibleCandidate.d \
./src/auxi/LKH/KSwapKick.d \
./src/auxi/LKH/LinKernighan.d \
./src/auxi/LKH/LKH_Lib.d \
./src/auxi/LKH/Make2OptMove.d \
./src/auxi/LKH/Make3OptMove.d \
./src/auxi/LKH/Make4OptMove.d \
./src/auxi/LKH/Make5OptMove.d \
./src/auxi/LKH/MakeKOptMove.d \
./src/auxi/LKH/MergeTourWithBestTour.d \
./src/auxi/LKH/MergeWithTourGPX2.d \
./src/auxi/LKH/MergeWithTourIPT.d \
./src/auxi/LKH/Minimum1TreeCost.d \
./src/auxi/LKH/MinimumSpanningTree.d \
./src/auxi/LKH/MTSP2TSP.d \
./src/auxi/LKH/MTSP_InitialTour.d \
./src/auxi/LKH/MTSP_Report.d \
./src/auxi/LKH/MTSP_WriteSolution.d \
./src/auxi/LKH/NormalizeNodeList.d \
./src/auxi/LKH/NormalizeSegmentList.d \
./src/auxi/LKH/OrderCandidateSet.d \
./src/auxi/LKH/PatchCycles.d \
./src/auxi/LKH/PDPTW_Reduce.d \
./src/auxi/LKH/Penalty_1_PDTSP.d \
./src/auxi/LKH/Penalty_ACVRP.d \
./src/auxi/LKH/Penalty_BWTSP.d \
./src/auxi/LKH/Penalty_CCVRP.d \
./src/auxi/LKH/Penalty_CTSP.d \
./src/auxi/LKH/Penalty_CVRP.d \
./src/auxi/LKH/Penalty_CVRPTW.d \
./src/auxi/LKH/Penalty_M1_PDTSP.d \
./src/auxi/LKH/Penalty_MLP.d \
./src/auxi/LKH/Penalty_M_PDTSP.d \
./src/auxi/LKH/Penalty_MTSP.d \
./src/auxi/LKH/Penalty_OVRP.d \
./src/auxi/LKH/Penalty_PDPTW.d \
./src/auxi/LKH/Penalty_PDTSP.d \
./src/auxi/LKH/Penalty_PDTSPF.d \
./src/auxi/LKH/Penalty_PDTSPL.d \
./src/auxi/LKH/Penalty_RCTVRP.d \
./src/auxi/LKH/Penalty_SOP.d \
./src/auxi/LKH/Penalty_TRP.d \
./src/auxi/LKH/Penalty_TSPDL.d \
./src/auxi/LKH/Penalty_TSPPD.d \
./src/auxi/LKH/Penalty_TSPTW.d \
./src/auxi/LKH/Penalty_VRPB.d \
./src/auxi/LKH/Penalty_VRPBTW.d \
./src/auxi/LKH/Penalty_VRPPD.d \
./src/auxi/LKH/printff.d \
./src/auxi/LKH/PrintParameters.d \
./src/auxi/LKH/Random.d \
./src/auxi/LKH/ReadCandidates.d \
./src/auxi/LKH/ReadEdges.d \
./src/auxi/LKH/ReadLine.d \
./src/auxi/LKH/ReadParameters.d \
./src/auxi/LKH/ReadPenalties.d \
./src/auxi/LKH/ReadProblem.d \
./src/auxi/LKH/RecordBestTour.d \
./src/auxi/LKH/RecordBetterTour.d \
./src/auxi/LKH/RemoveFirstActive.d \
./src/auxi/LKH/ResetCandidateSet.d \
./src/auxi/LKH/RestoreTour.d \
./src/auxi/LKH/SegmentSize.d \
./src/auxi/LKH/Sequence.d \
./src/auxi/LKH/SFCTour.d \
./src/auxi/LKH/SINTEF_WriteSolution.d \
./src/auxi/LKH/SolveCompressedSubproblem.d \
./src/auxi/LKH/SolveDelaunaySubproblems.d \
./src/auxi/LKH/SolveKarpSubproblems.d \
./src/auxi/LKH/SolveKCenterSubproblems.d \
./src/auxi/LKH/SolveKMeansSubproblems.d \
./src/auxi/LKH/SolveRoheSubproblems.d \
./src/auxi/LKH/SolveSFCSubproblems.d \
./src/auxi/LKH/SolveSubproblemBorderProblems.d \
./src/auxi/LKH/SolveSubproblem.d \
./src/auxi/LKH/SolveTourSegmentSubproblems.d \
./src/auxi/LKH/SOP_InitialTour.d \
./src/auxi/LKH/SOP_RepairTour.d \
./src/auxi/LKH/SOP_Report.d \
./src/auxi/LKH/Statistics.d \
./src/auxi/LKH/StatusReport.d \
./src/auxi/LKH/StoreTour.d \
./src/auxi/LKH/SymmetrizeCandidateSet.d \
./src/auxi/LKH/TrimCandidateSet.d \
./src/auxi/LKH/TSPDL_InitialTour.d \
./src/auxi/LKH/TSPTW_MakespanCost.d \
./src/auxi/LKH/TSPTW_Reduce.d \
./src/auxi/LKH/VRPB_Reduce.d \
./src/auxi/LKH/WriteCandidates.d \
./src/auxi/LKH/WritePenalties.d \
./src/auxi/LKH/WriteTour.d

_DEPS = Delaunay.h GainType.h Genetic.h GeoConversion.h Hashing.h      \
        Heap.h LKH.h Segment.h Sequence.h BIT.h gpx.h LKH_Lib.h

DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

# Each subdirectory must supply rules for building sources it contributes
src/auxi/LKH/%.o: ../src/auxi/LKH/%.c $(DEPS)
	@echo 'Building file: $<'
	@echo 'Invoking: Cross G++ Compiler'
	gcc -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<" $(CFLAGS)
	@echo 'Finished building: $<'
	@echo ' '
